#!/usr/bin/python
import os,urllib2,StringIO,getpass

# VARS
# Must be improved with Json format, easier for parsing
url = "http://ip-api.com/line/?fields=query,city,lat,lon"
asciiworld_bin = "/usr/local/asciiworld"
######
filename = "/tmp/asciiworld-latlong-%s"%(getpass.getuser())
tmp_file = open(filename,"w")
latlong = []
for i in StringIO.StringIO(urllib2.urlopen(url).read()):
    latlong.append(i)
# Ugly...
tmp_file.write("points\n")
tmp_file.write(latlong[1].rstrip()+" "+latlong[2])
tmp_file.close()
print filename
os.system("/usr/local/bin/asciiworld -l "+filename)

# Print your IP, and city
print latlong[0].rstrip()+" --> "+latlong[3]
